# Generated by Django 4.2.23 on 2025-08-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_imagepath_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Best Sellers', 'Best Sellers'), ('New Arrivals', 'New Arrivals'), ('Hot Sales', 'Hot Sales')], max_length=15),
        ),
    ]
