# Generated by Django 4.2.23 on 2025-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new-arrivals', 'New Arrivals'), ('hot-sales', 'Hot Sales')], default='new-arrivals', max_length=15),
            preserve_default=False,
        ),
    ]
